[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
skip = ["staticfiles", "media", ".venv", "venv", "migrations"]
known_first_party = ["base", "base_backend"]
